from prometheus_client import Counter, Histogram, Gauge

INCIDENTS_CREATED = Counter("aegisops_incidents_created_total", "Total incidents created", ["severity", "service"])
INCIDENT_STATUS = Gauge("aegisops_incidents_by_status", "Current incidents by status", ["status"])
RCA_REQUESTS = Counter("aegisops_rca_requests_total", "Total RCA analyses requested")
RCA_LATENCY = Histogram("aegisops_rca_latency_seconds", "Latency of RCA analysis")
AGENT_LATENCY = Histogram("aegisops_agent_latency_seconds", "Agent execution latency", ["agent"])
RUNBOOK_EXECUTIONS = Counter("aegisops_runbook_executions_total", "Total runbook executions", ["runbook"])
RUNBOOK_REJECTIONS = Counter("aegisops_runbook_rejections_total", "Total runbook executions rejected")
AI_CONFIDENCE_SCORE = Gauge("aegisops_ai_confidence_score", "Latest AI RCA confidence score")
TOOL_FAILURES = Counter("aegisops_tool_failures_total", "Tool failures by tool name", ["tool"])
EVAL_SCORE = Gauge("aegisops_latest_eval_score", "Latest benchmark evaluation score")
INFEROPS_CALLS = Counter("aegisops_inferops_calls_total", "Total InferOps AI gateway calls", ["status"])
OPENAI_CALLS = Counter("aegisops_openai_calls_total", "Total direct OpenAI chat-completion calls", ["status"])
SERVICE_FAULTS = Counter("aegisops_service_faults_total", "Faults injected into monitored services", ["service", "mode"])

LOKI_QUERIES = Counter("aegisops_loki_queries_total", "Loki log-search queries", ["status"])
K8S_ADAPTER_CALLS = Counter("aegisops_k8s_adapter_calls_total", "Kubernetes adapter calls", ["status"])
NOTIFICATIONS_SENT = Counter("aegisops_notifications_sent_total", "Notifications sent or simulated", ["channel", "status"])
RAG_QUERIES = Counter("aegisops_rag_queries_total", "RAG memory queries", ["source"])
MODEL_LATENCY = Histogram("aegisops_model_latency_seconds", "InferOps/model call latency", ["provider", "model"])
MODEL_COST = Counter("aegisops_model_cost_usd_total", "Accumulated model cost in USD", ["provider", "model"])
MODEL_TOKENS = Counter("aegisops_model_tokens_total", "Model tokens by type", ["provider", "model", "token_type"])
